version: 0.2

phases: 
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install cfn-lint taskcat
  build:
    commands:
      - echo "Bắt đầu build..."
      - cfn-lint modules/main.yaml
artifacts:
  files:
    - modules/*.yaml